# Generated by Django 4.2.17 on 2025-04-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='code',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('DEFAULT', 'Не назначена'), ('student', 'Студент'), ('teacher', 'Преподаватель'), ('curator', 'Куратор'), ('customer', 'Заказчик'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='DEFAULT', max_length=20, verbose_name='Должность'),
        ),
    ]
